### ISSUE TITLE
build_cmd breaks with AttributeError: 'tuple' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by pmourlanne** [SublimeLinter/SublimeLinter3#395]
The commit https://github.com/SublimeLinter/SublimeLinter3/commit/c4f8e7b1fc2d1c7a5eb749a4fef355bd7a66ff16 broke my build.

Here is the full stack trace:
```
Traceback (most recent call last):
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 924, in lint_view
    linter.lint(hit_time)
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1369, in lint
    cmd = self.get_cmd()
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1119, in get_cmd
    return self.build_cmd()
  File "/home/pmourlanne/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1171, in build_cmd
    cmd[0:1] = util.convert_type(os.path.abspath(path), [])
  File "./posixpath.py", line 379, in abspath
  File "./posixpath.py", line 64, in isabs
AttributeError: 'tuple' object has no attribute 'startswith'
```

The issue is that `path`, in my case, is equals to `('/usr/bin/python3', '/usr/local/bin/pyflakes')`.

(A fix for me was to rollback the offending commit)

**Comment by grotewold** [comment]
I just pushed 618e371e69d034eeea60e206add89d02b4e832cd, could you check that this does in fact correct your issue. I've done some tests, but want to double check. Thanks!

**Comment by grotewold** [comment]
did a little more testing and feel relatively safe. Pushed in v3.6.1

Reopen or comment here if this issue is not resolved once you have tested v3.6.1

**Comment by pmourlanne** [comment]
I just upgraded to 3.6.1 and it works again.

Thanks!
